//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace LogicaNegocio.wsInicio {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WsInicioSesionSoap", Namespace="http://tempuri.org/")]
    public partial class WsInicioSesion : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CrearUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback verificarUsuarioOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WsInicioSesion() {
            this.Url = global::LogicaNegocio.Properties.Settings.Default.LogicaNegocio_WsInicioSesion_WsInicioSesion;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CrearUsuarioCompletedEventHandler CrearUsuarioCompleted;
        
        /// <remarks/>
        public event verificarUsuarioCompletedEventHandler verificarUsuarioCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CrearUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CrearUsuario(string Nomusuario, string Contrasenia, int codEmpresa, string Instancia) {
            object[] results = this.Invoke("CrearUsuario", new object[] {
                        Nomusuario,
                        Contrasenia,
                        codEmpresa,
                        Instancia});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CrearUsuarioAsync(string Nomusuario, string Contrasenia, int codEmpresa, string Instancia) {
            this.CrearUsuarioAsync(Nomusuario, Contrasenia, codEmpresa, Instancia, null);
        }
        
        /// <remarks/>
        public void CrearUsuarioAsync(string Nomusuario, string Contrasenia, int codEmpresa, string Instancia, object userState) {
            if ((this.CrearUsuarioOperationCompleted == null)) {
                this.CrearUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrearUsuarioOperationCompleted);
            }
            this.InvokeAsync("CrearUsuario", new object[] {
                        Nomusuario,
                        Contrasenia,
                        codEmpresa,
                        Instancia}, this.CrearUsuarioOperationCompleted, userState);
        }
        
        private void OnCrearUsuarioOperationCompleted(object arg) {
            if ((this.CrearUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrearUsuarioCompleted(this, new CrearUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/verificarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string verificarUsuario(string nombre, string contrasena) {
            object[] results = this.Invoke("verificarUsuario", new object[] {
                        nombre,
                        contrasena});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void verificarUsuarioAsync(string nombre, string contrasena) {
            this.verificarUsuarioAsync(nombre, contrasena, null);
        }
        
        /// <remarks/>
        public void verificarUsuarioAsync(string nombre, string contrasena, object userState) {
            if ((this.verificarUsuarioOperationCompleted == null)) {
                this.verificarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnverificarUsuarioOperationCompleted);
            }
            this.InvokeAsync("verificarUsuario", new object[] {
                        nombre,
                        contrasena}, this.verificarUsuarioOperationCompleted, userState);
        }
        
        private void OnverificarUsuarioOperationCompleted(object arg) {
            if ((this.verificarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.verificarUsuarioCompleted(this, new verificarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void CrearUsuarioCompletedEventHandler(object sender, CrearUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrearUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CrearUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void verificarUsuarioCompletedEventHandler(object sender, verificarUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class verificarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal verificarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591